# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Just Right There' do
    pod 'CSStickyHeaderFlowLayout'
    pod 'Firebase', '>= 2.4.2'
    pod 'DZNEmptyDataSet'
end

target 'Just Right ThereTests' do

end

