# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Just Right There' do
    pod "CSStickyHeaderFlowLayout"
end

target 'Just Right ThereTests' do

end

